### ISSUE TITLE
SSL support for MapQuest OSM

### ISSUE THREAD

**Issue by rbaprado** [leaflet-extras/leaflet-providers#116]
I know that MapQuest OSM supports SSL, but the provider URL seems to be hardcoded to 'http', this is triggering mixed-content warnings on my site (which is SSL-only).

**Comment by jieter** [comment]
It seems they have a problem with the certificate for this url:

https://otile3.mqcdn.com/tiles/1.0.0/map/9/261/169.jpeg

![2015-02-26-175911_684x547_scrot](https://cloud.githubusercontent.com/assets/1470389/6396843/34b6bea8-bde1-11e4-9690-2008f18de98b.png)

**Comment by jieter** [comment]
Interesting: 
https://www.drupal.org/files/openlayers-mapquest-https.patch

**Comment by jieter** [comment]
This makes it impossible to use protocol relativity for mapquest urls... Adding a comment in the source.

**Comment by ximex** [comment]
I try to some this up. There are 3 possible urls:
- **HTTP:** `http://otile{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.{ext}`
- **HTTPS (untrusted cert):** `https://otile{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.{ext}`
- **HTTPS (trusted cert):** `https://otile{s}-s.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.{ext}`

Some has to write to mapquest that they should use a trusted certificat on their server at `https://otile{s}.mqcdn.com`

**Comment by jieter** [comment]
Yeah, right. But untrusted doesn't help much, you are better off using http. Let's see if they are awake on twitter.
