### ISSUE TITLE
List of previews can't be scroll on tablet browser

### ISSUE THREAD

**Issue by Aplies** [leaflet-extras/leaflet-providers#120]
Hello !!

On Android tablet, I can't scroll the previews list. It detects the scroll on the map and not on the previews list. I tried to play with the CSS "z-index", "overflow", ect... But it doesn't work. I know the previews implementation is just a demo but i'm not really good in CSS tricks.
(I tried on firefox android, chrome android, default android browser)

It's not really an issue but If someone has an idea to help me... thanks in advance.

(and sorry for my bad english...)

**Comment by jieter** [comment]
Unfortunately, I've got no tablet to test on...

**Comment by brunob** [comment]
no tablet here too :\

**Comment by jieter** [comment]
possibly related: https://github.com/Leaflet/Leaflet/issues/2882

**Comment by ximex** [comment]
i could confirm the problem on android 4.4 firefox nightly (nexus 4)

**Comment by jieter** [comment]
This is a leaflet-layerscontrol-minimap-bug, I opened an issue there.
