### ISSUE TITLE
Basemap.at

### ISSUE THREAD

**Issue by ximex** [leaflet-extras/leaflet-providers#124]
Should we also include layers that didn't cover the whole earh?
I need the Basemap.at layer very often (from Austria)
http://basemap.at/

If yes we have to set the bounds, what shouldn't be a problem.

Example:

```javascript
Basemap: {
      url: '//maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.jpeg',
      options: {
        HTTPS: true,
        attribution: 'Datenquelle: <a href="//www.basemap.at">basemap.at</a>',
        subdomains: ['', '1', '2', '3', '4'],
        bounds: [[46.358770, 8.782379], [49.037872, 17.189532]]
      },
      variants: {
        basemap: 'geolandbasemap',
        bmapgrau: 'bmapgrau',
        bmapoverlay: 'bmapoverlay',
        bmaphighdpi: 'bmaphidpi'
      }
    }
```

**Comment by jieter** [comment]
Why not, we already have US-only maps.

Note that `Basemap` might be a bit broad as an identifier

**Comment by ximex** [comment]
hmmm i can change this to 'geolandbasemap'. But the map is named 'basemap'
