### ISSUE TITLE
npm run test

### ISSUE THREAD

**Issue by ximex** [leaflet-extras/leaflet-providers#126]
this command didn't work for me. I think he didn't like the * expression.
Windows 7 x64

```
npm run test
> leaflet-providers@1.0.14 test C:\############\leaflet-providers
> jshint leaflet-providers.js preview/*.js
ERROR: Can't open preview/*.js
```

**Comment by jieter** [comment]
It's mostly there for travis-ci and works perfectly on ubuntu/OSX. You can easily run the command without the last part to verify only `leaflet-providers.js`
