### ISSUE TITLE
Publish latest version to https://cdnjs.com/libraries/leaflet-providers

### ISSUE THREAD

**Issue by paazmaya** [leaflet-extras/leaflet-providers#132]
Seems that currently the latest available from the CDNJS is `1.0.7` while the latest tag in the repo points to `1.0.15`.

Any chance of pushing the latest release over to https://cdnjs.com/libraries/leaflet-providers ?

**Comment by ximex** [comment]
Make a pull request at https://github.com/cdnjs/cdnjs

**Comment by ximex** [comment]
if #131 is merged, i will do the pull request at cdnjs

**Comment by jieter** [comment]
Should be possible to let it auto-update:

https://github.com/cdnjs/cdnjs#enabling-npm-auto-update

**Comment by ximex** [comment]
#133

**Comment by ximex** [comment]
Auto update is merged. We have to wait if this auto-update works

**Comment by paazmaya** [comment]
Thanks @ximex !

**Comment by jieter** [comment]
Doesn't seem to work...

**Comment by ximex** [comment]
Maybe this helps: https://github.com/cdnjs/cdnjs/issues/3638
looks like that this was the old way

**Comment by ximex** [comment]
Looks good: https://www.npmjs.com/package/leaflet-providers
close?

**Comment by jieter** [comment]
It certainly is on npm, but not on https://cdnjs.com/libraries/leaflet-providers

**Comment by ximex** [comment]
Oops. I have some missing sleep^^ My fault ;-)

**Comment by ximex** [comment]
but yet it should be fixed ;-)
https://cdnjs.com/libraries/leaflet-providers
Or did you push it manually?

**Comment by jieter** [comment]
Nice.

**Comment by paazmaya** [comment]
Now nice :smiley:
