### ISSUE TITLE
Question: Would this replace the need for MapQuest leaflet plugin?

### ISSUE THREAD

**Issue by amnesia7** [leaflet-extras/leaflet-providers#145]
I'm using the open mapquest maps. I'm using the mapquest js file but only using it for the map layers: `layers: MQ.mapLayer()`.

Does this code / the code in @mourner [gist](https://gist.github.com/mourner/1804938) remove the need to use the mapquest leaflet plugin?

The [leaflet plugin](http://developer.mapquest.com/en_GB/web/documentation/plugins/leaflet/v1.0/open) also requires the js file request to include my api key. Is that not necessary using your code instead?

**Comment by jieter** [comment]
Hmm, I'm not sure if MapQuest allows the use of their tile layers without the api key, like with this project, but it's [certainly possible](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=MapQuest), but [this indicates they do](http://wiki.openstreetmap.org/wiki/MapQuest).

The API key is not used as part of the url, but they load a 'TransactionImage', containing the key and some data about the map currently in use (center, size, Leaflet version, etc.)

**Comment by amnesia7** [comment]
@jieter I emailed the mapquest team for confirmation. 
I was told that it was not necessary to use their leaflet plugin and to check here (http://developer.mapquest.com/web/products/open/map) for more info about loading the map tiles. 
I also asked about the attribution required on the map (since their plugin takes care of this) and was directed toward http://developer.mapquest.com/web/products/open/map#terms.
That clears up for me that the map tiles can be loaded using the script rather than requiring the full mapquest leaflet plugin so closing this issue.
