### ISSUE TITLE
maxZoom

### ISSUE THREAD

**Issue by ximex** [leaflet-extras/leaflet-providers#152]
OSM Mapnik have Zoom 0-19.
I think MapQuest too.
See: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers

BasemapAT have 0-19 too.

**Comment by jieter** [comment]
I'll merge a PR adjusting the (min|max)Zoom values...

**Comment by ximex** [comment]
We only ned the maxZoom.
Default minZoom=0 and maxZoom=18

**Comment by ximex** [comment]
this should be mostly all.

**Comment by jieter** [comment]
So can we close this for now?
