### ISSUE TITLE
Commonjs / Browserify

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#166]
With #162, we have AMD support. 

Do we need to add:  
```JavaScript:
    // define a Common JS module that relies on 'leaflet'
    } else if (typeof exports === 'object') {
        module.exports = factory(require('leaflet'));
    }
```

**Comment by brunob** [comment]
no idea sorry :\

**Comment by calvinmetcalf** [comment]
you want to check that both module and exports exist

**Comment by jieter** [comment]
Hmm, sorry for my question being unclear, I intended to ask about the need of implementing the commonjs module.
