### ISSUE TITLE
Add support for OS OpenSpace

### ISSUE THREAD

**Issue by mvl22** [leaflet-extras/leaflet-providers#168]
The Ordnance Survey is the UK mapping agency for Great Britain. They have a open data product line which includes map tiles.

Recently they have posted code to enable their tiles to be loaded using Leaflet.js:

https://www.ordnancesurvey.co.uk/forums/discussion/1001864/using-leafletjs-with-openspace#1013226

It would be good to put this into the leaflet-providers repo.

**Comment by jieter** [comment]
Hi @mvl22, good suggestion. Can you make a PR?

**Comment by jieter** [comment]
Hmm, might not be straightforward if these layers use a nonstandard projection

**Comment by jieter** [comment]
This is not going to happen in leaflet-providers. Too much code needed for just one layer. Use https://github.com/rob-murray/os-leaflet.
