### ISSUE TITLE
detectRetina not working for NASAGIBS.ViirsEarthAtNight2012

### ISSUE THREAD

**Issue by neothemachine** [leaflet-extras/leaflet-providers#169]
When I use `detectRetina: true` for NASAGIBS.ViirsEarthAtNight2012 it somehow changes the maxZoom from 8 to 7 which in turn requests the wrong tile URLs (404). Using detectRetina works perfectly for other basemaps like Esri.WorldImagery.

**Comment by jieter** [comment]
Hmm, not sure what we could do about it. Are your sure it's not a Leaflet bug?

**Comment by neothemachine** [comment]
I've no clue to be honest.

**Comment by jieter** [comment]
This is how `detectRetina` works: it requests 4 tiles from a lower zoom level to get a higher resolution: https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L28-L35
