### ISSUE TITLE
The Historical Map of Great Britain

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#178]
National library of Scotland has this: http://nls.tileserver.com/

Very nice 1920 ~ 1940 maps

http://maps.nls.uk/projects/api/

**Comment by brunob** [comment]
Nice tiles +1

**Comment by brunob** [comment]
Following https://github.com/leaflet-extras/leaflet-providers/issues/190#issuecomment-152276891 i'm not sure we can porvide this layers, since : 

> Direct access to the tiles via the http://nls.tileserver.com/ URL is not recommended - please use our JavaScript API if possible. The location of the tiles is subject to change in future and the JavaScript API will reflect this change and provide basic load balancing. Use of our online service or tiles in commercial websites or applications (iPhone apps, ..) must be confirmed from our side! 

http://maps.nls.uk/projects/api/

**Comment by jieter** [comment]
Hmm, [NLS interacted with me on twitter](https://twitter.com/natlibscotmaps/status/649916230913159168), but did not respond to my question if I added subscription-only layers: 

'...is not recommended' to me doesn't sound like it's not allowed. In fact, further in the page, only attribution is required:
![2015-10-30-104244_756x541_scrot](https://cloud.githubusercontent.com/assets/1470389/10842580/000a7a90-7ef3-11e5-8474-a574fa8f6198.png)

They also recommend contacting them by email, I'll do that and ask their opinion.

**Comment by brunob** [comment]
Nice, thx for that @jieter

**Comment by jieter** [comment]
Just sent the email, reopened until this is fixed.
