### ISSUE TITLE
Broken providers?

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#184]
- [ ] Stamen.TopOSM seems to be broken `GET http://stamen-tiles-a.a.ssl.fastly.net/toposm-color-relief/4/2/6.png 404 (Not Found)`
- [x] freemap.sk needs bounds + maxzoom

**Comment by brunob** [comment]
toposm tiles seems to be available here : http://b.tile.stamen.com/toposm-color-relief/5/7/12.jpg

**Comment by jieter** [comment]
Hmm, strange [they're not on the ssl.fastly.net domain](http://maps.stamen.com/#usage-ssl). We can add an exception for this layer to always use the `http`-url...

**Comment by jieter** [comment]
Hmm http://stamen-tiles-a.a.ssl.fastly.net/toposm-color-relief/5/7/12.jpg, both over ssl and plain http.

Might be another issue then? Or just temporal errors.

**Comment by brunob** [comment]
indeed jpg != png ;)

http://stamen-tiles-{s}.a.ssl.fastly.net/toposm-color-relief/{z}/{x}/{y}.png

http://leaflet-extras.github.io/leaflet-providers/preview/#filter=TopOSM

**Comment by jieter** [comment]
hmm, there [is an ext: 'jpg' in the options, but no `{ext}` in the url](https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js#L250-L260). Strange.

**Comment by brunob** [comment]
https://github.com/leaflet-extras/leaflet-providers/commit/0f8864f27fdb27fedcaca33f72f48981155b472e change introducing this, i think we can put back {ext} in the url template.

**Comment by jieter** [comment]
I'm on it.

**Comment by jieter** [comment]
hmm, not careful enough copied from https://github.com/leaflet-extras/leaflet-providers/pull/153/files

**Comment by jieter** [comment]
released v1.1.5
