### ISSUE TITLE
Tile usage policies

### ISSUE THREAD

**Issue by Monduiz** [leaflet-extras/leaflet-providers#190]
I am trying to find clear information about the providers. The data on all OSM tiles is free to use for everyone but its with the existing tile servers that things are unclear for me. Let's say I like the OSM mapnik b&W tiles that are hosted by wikimedia labs. Can I go to production with these? I am now trying to decide if I have to go with a tile server or use an existing one. Its unclear how to reach the folks at wikimedia.

**Comment by brunob** [comment]
This script is compliant with the TOS of every proposed providers, we have also contacted some of them to ask if they are ok to be listed in the script. So you can use these providers safely in your project.

**Comment by jieter** [comment]
It does depend on the amount you of traffic you are about to generate as some providers have usage limits. If you expect much traffic, make sure to check that before deploying.

**Comment by Monduiz** [comment]
Well, it's going to be a lot of traffic. The tiles I'm interested in are those hosted by wikimedia labs, the OSM black and white. I might need to see about getting a set where states, provinces are in French too.

**Comment by brunob** [comment]
@Monduiz you should read this first http://wiki.openstreetmap.org/wiki/Tile.openstreetmap.org/Usage_policy + contact osm techs on irc http://wiki.openstreetmap.org/wiki/FR:IRC

You'll may need to install your own tileserver if you want other language for labels, or you can merge two tiles sources with tools like tilestache, i've wrote a post about that here http://labo.eliaz.fr/article123.html

**Comment by RobJN** [comment]
@brunob That's not quite right. The National Library of Scotland has a free API (at http://maps.nls.uk/projects/api/index.html ) and a subscription API (at http://maps.nls.uk/projects/subscription-api/). Currently I think you are providing some layers (e.g. London) that aren't part of the free API. NLS have indicated that some small non-commercial use may be ok but you need to ask first. End users should implement the NLS maps themselves after receiving the required permission.

**Comment by brunob** [comment]
@RobJN to be more clear, i'm sure that i've done it for every tiles sources i've proposed or added. Anyway, thanks for the clarification on NLS tiles, i'll look in pull request history to find out how these have been integred, and we surely need to contact NLS to clarify the situation @jieter (?)

**Comment by brunob** [comment]
Ok #178 introduced these tiles.

**Comment by jieter** [comment]
I think we can close this after #193?

**Comment by brunob** [comment]
(y) @jieter
