### ISSUE TITLE
NLS map tiles are not free

### ISSUE THREAD

**Issue by RobJN** [leaflet-extras/leaflet-providers#192]
Some of the NLS map layers being included are not part of the free API (http://maps.nls.uk/projects/api/index.html). I believe this applies to OS_1900, OS_OpenData, OS_25k, OS_London, OS_6... and OS_7... layers. They should be removed so that you don't mislead others in to thinking they are free.

**Comment by RobJN** [comment]
I should add that the NLS have introduced their subscription service as a way to cover the costs of serving the map tiles. The costs have increased as the number of users have increased and commercial entities should be paying the nominal subscription fee. Small non-commercial users can of course contact NLS.

**Comment by jieter** [comment]
Thanks for addressing this, please discuss in #178
