### ISSUE TITLE
HERE app_ID is exceeding transaction limit

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#194]
Just received an email from HERE that the `app_ID` used in the leaflet-providers preview is exceeding their limits:

> Your app_ID is exceeding the transaction limit of your HERE Consumer Free plan in our Customer Integration Test (CIT) environment.
>  
> To continue to use the app_ID associated with this plan, please upgrade now to a paid plan that meets your needs.

When I log in, my account shows I'm on the *consumer free plan* with *100,000 monthly transactions*. This is the graph showing the usage:
![2015-11-03-171249_1028x480_scrot](https://cloud.githubusercontent.com/assets/1470389/10913443/367289de-824e-11e5-9146-3ebb83b65a73.png)

Seems I have another email to write...

We can also reduce the number of requests by removing some of the layers from the preview as that might be causing some of the traffic.

**Comment by brunob** [comment]
Think on or two here layers are enough for demo page. And maybe we can use tow app_ID (on for each layer) ?

**Comment by jieter** [comment]
Added fresh API keys and reduced the number of preview layers to 3 for HERE in #209
