### ISSUE TITLE
More information about the "free" providers

### ISSUE THREAD

**Issue by derwaldgeist** [leaflet-extras/leaflet-providers#197]
I'm a bit puzzled about the term "free providers". For instance, your providers demo includes "Thunderforest" and this provider is also not listed under your section "Providers requiring registration".  So I thought it is completely free. If I look at their homepage, they state that the free plan is limited to 150.000 tiles per month, and I can see additional plans for higher volumes.

Now I compared that to the HERE provider's offer. As you mention, this provider requires a registration. But if you register, you will get 100.000 transactions for free, which - if I understand their terms correctly - translates to ~ 1.500.000 tile requests. So, at least to me it seems as if their free"plan is more attractive than Thunderforest's.

This is why I think that this statement is a bit misleading:
```
In addition to the providers you are free to use, 
we support some layers which require registration.
```
as it implies that the "free" providers don't require any registration, even if you need larger volumes.

It would be very helpful if the repo description would include a bit more information about the usage terms and conditions of each supported provider, at least on a "high-level view" (pricing model, terms of the free tier), maybe including links to the respective details on their websites.

I know this might be a bit hard to keep this information up-to-date, but you could also add an "as of >date<, subject to change" disclaimer.

I think it should also be worth mentioning that the OpenStreeMap servers disencourage the use for higher volumes / productive apps, they even say they might ban you if you overuse it, as described here:

http://wiki.openstreetmap.org/wiki/Tile_usage_policy

So although they are "free", there's still a limitation, and I think this should be mentioned as well.

**Comment by brunob** [comment]
Hi,
> I know this might be a bit hard to keep this information up-to-date, but you could also add an "as of >date<, subject to change" disclaimer.

As you said, i think this kind of list will be hard to maintain, and since we are linking every provider in the credits, every one can find this kink of information on the provider website.

Anyway, maybe we can try to make a list of simple links to provider tile usage policy in the readme. Any thoughts about it ?

**Comment by derwaldgeist** [comment]
Yes, I think having links to the tile usage policy would be a good start.

My main point, however, was to avoid to have "misleading" statements in the readme which might give you the impression that some of providers are completely free, while they aren't.

**Comment by brunob** [comment]
@derwaldgeist feel free to provide the list in the README from a pull request
