### ISSUE TITLE
￼ OpenStreetMap.BlackAndWhite down

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#199]
￼ OpenStreetMap.BlackAndWhite seems unavailable.

**Comment by brunob** [comment]
I'll investigate to see if it's a temporary or definitive problem.

**Comment by Monduiz** [comment]
Yes, I came here to see what is going on with the wikimedia labs tiles. We are using them for development and they have been down for a few days now. Incidentally, I am looking for the style sheet for these because they are perfect for choropleth maps.

**Comment by brunob** [comment]
@Monduiz i don't got anything new about it for now... Meanwhile you could use OpenMapSurfer.Grayscale or CartoDB.Positron.

**Comment by Monduiz** [comment]
Thanks for the suggestions! I will look them up.

The tiles from wikimedia labs appear to be back online by the way.

**Comment by brunob** [comment]
Nice to read that, maybe we can close the issue @jieter or wait a bit to see if the are really back ?

**Comment by jieter** [comment]
I'll chime in with a new issue if I discover them down again...
