### ISSUE TITLE
New thunderforest tiles

### ISSUE THREAD

**Issue by brunob** [leaflet-extras/leaflet-providers#200]
We may add theses tiles just for fun :p 

http://thunderforest.com/maps/spinal-map/

https://[abc].tile.thunderforest.com/spinal-map/{z}/{x}/{y}.png

**Comment by brunob** [comment]
And this one too : http://thunderforest.com/maps/pioneer/

https://[abc].tile.thunderforest.com/pioneer/{z}/{x}/{y}.png

**Comment by brunob** [comment]
Hey @jieter we are cited in latest weekly osm :) 

> There are many map styles and specialized overlays which can be added to Leaflet maps using the Leaflet Providers extension. Now you can view nice mini-maps of all these styles here.

http://www.weeklyosm.eu/archives/6291

**Comment by jieter** [comment]
Nice ;)
