### ISSUE TITLE
style sheet

### ISSUE THREAD

**Issue by Monduiz** [leaflet-extras/leaflet-providers#202]
I have a question about style sheets. The style for the wikimedia labs black and white tiles used to be available here: https://github.com/mapnik/mapnik/wiki/StyleShare

Any idea how or if it is available anywhere? Are the people with this project at wikimedia labs willing to share it?

**Comment by jieter** [comment]
No idea, maybe more luck if you ask the mapnik or wikimedia guys

https://github.com/wikimedia/
