### ISSUE TITLE
Question Around Esri Licensing

### ISSUE THREAD

**Issue by emwalters** [leaflet-extras/leaflet-providers#204]
In the README file, you write: “In order to use ArcGIS maps, you must register and abide by the terms of service. No special syntax is required.”, but with your plugin, there’s no way for Esri to verify that you’re actually registered (such as by sending an API key or authentication token).

Is Esri asking us to register on the honor system?  Or am I just missing something here?

Sorry if any of this seems obvious, this is my first foray into the world of GIS.

**Comment by emwalters** [comment]
I found this information on http://www.esri.com/data/basemaps 

>ArcGIS Online Basemaps
> Delivered as map services, these basemaps and reference layers are freely available to anyone and include World Imagery, World Street Map, World Topographic, Ocean Basemap, and more.

So it seems like the map tile variants that you're offering through your plugins are "freely available to anyone", though I'm not sure what impact that has on the "you must register" piece.

**Comment by brunob** [comment]
Have you made a search and seen #22 ?

**Comment by emwalters** [comment]
No, I hadn't seen it.  Thank you for linking me to that.

So, if I have an app that falls under the "paid subscription" model in their terms of use (such as an enterprise app that would generate revenue), does your plugin support that?  Or would I need to use Esri's JavaScript API to access the map tiles?

**Comment by emwalters** [comment]
Maybe this question is more appropriate for an Esri representative.  I'll contact them directly and see what they recommend.  Thanks for your help.

**Comment by brunob** [comment]
@emwalters that's exactly what i was thinking about ;) Feel free to provide info from esri in this issue after you contact them.

**Comment by abdulrazakbg** [comment]
Can we use below snippet to fetch tile layer without API key for enterprise application ?

var Esri_WorldTerrain = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}', {
	attribution: 'Tiles &copy; Esri &mdash; Source: USGS, Esri, TANA, DeLorme, and NPS',
	maxZoom: 13
});

**Comment by hhkaos** [comment]
Hi everyone!,

A friend sent me this issue, asking for help to clarify. 

I work at the developer experience team at Esri (not for the legal team), so there may be a gap in my knowledge, but if you want I can contact the legal team to confirm.

To my knowledge, the unauthenticated endpoints provided by Esri can be used by Esri customers using ArcGIS Online, ArcGIS Pro, and a few other products, but can not be used by non-Esri customers.

That been said. What I'm sure is that any developer can create a free account at https://location.arcgis.com/ and use the authenticated endpoints which today include 2,000,000 free monthly tiles for commercial and non-profit use. For those exceeding that amount will have to introduce a credit card and will be charged per tiles used (as other corporate providers like AWS, Here, TomTom, etc)

I hope this helps. And I'm happy to send a PR if you want.

Cheers!

**Comment by brunob** [comment]
Hi @hhkaos and thx for these infos :)

> To my knowledge, the unauthenticated endpoints provided by Esri can be used by Esri customers using ArcGIS Online, ArcGIS Pro, and a few other products, but can not be used by non-Esri customers.

I think you are right : 

> Use with Esri software and comply with its terms of use. If you do not have Esri software, you must purchase an ArcGIS or Developer subscription

ref https://downloads2.esri.com/arcgisonline/docs/tou_summary.pdf

It's a pity but i think we should change endpoints to authenticated endpoints @jieter :\

@hhkaos can you get a confirmation from your legal team as you proposed ? And feel free to provide a PR with updated endpoints or simply providing the updated list here.
