### ISSUE TITLE
openweathermap legends

### ISSUE THREAD

**Issue by nFrechen** [leaflet-extras/leaflet-providers#211]
Great job with these easy to use leaflet provider tiles!

I would say that the providerTiles of openweathermap.org would benefit from a legend that can be added with a simple command. Else you can't really tell what you are looking at on the map and it is just a colorful display...

On there page they provide png legends for their tiles. For example:
Precipitation:
http://openweathermap.org/img/a/PR.png
Pressure:
http://openweathermap.org/img/a/PN.png

Here is a leaflet library that facilitates the png legends:
https://github.com/buche/leaflet-openweathermap

Another way would be to use their xml legend information and draw the legend:
http://openweathermap.org/map_legend

Do you think it is achievable to add a default option to add these legends?

**Comment by jieter** [comment]
I agree the tiles would benefit from a legend, but think it's a bit out of scope for the project: I suggest using the referenced project to add the layers to your map.

If you think you can provide a nice clean patch to add the legend, you're welcome to open a PR.

**Comment by nFrechen** [comment]
Sadly I don't know much about java script because I am using leaflet out of the R environment. They use your library to integrate providerTiles. I already had a look if I can recognize common features in the two implementations but did not understand a bit. I will see what I can do... Thanks for the answer anyway!
