### ISSUE TITLE
Add Traffic Layer from Google Map or somewhere else

### ISSUE THREAD

**Issue by karafede** [leaflet-extras/leaflet-providers#213]
I am trying integrating the TrafficLayer from Google Map into a Leaflet Map. 
From the Google API developer website, I could setup an API key to access to the .js script that "I think" is the TrafficLayer representing the current traffic flow from Google.
Something like that:

https://developers.google.com/maps/documentation/javascript/examples/layer-traffic

Now, How can I integrate the <script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"> into a leaflet map.
I can see that the above format is very similar to what is used to write leaflet maps in R but I cannot figure out the way to integrate the Java script into the map. Is perhaps necessary to download the .js file first and then trying to get the TrafficLayer out of there first.
If so, Is there a way to do this in R?

Thanks in advance for your suggestions
Federico

**Comment by brunob** [comment]
?

**Comment by jieter** [comment]
see #8, #16, for previous google layer issues, 

and https://github.com/shramov/leaflet-plugins for a google layer implementation.
