### ISSUE TITLE
Tilelayer addresses have changed.

### ISSUE THREAD

**Issue by JasonThomasData** [leaflet-extras/leaflet-providers#217]
Hi folks.

The tilelayers here have changed address.

EG- 
http://korona.geog.uni-heidelberg.de/tiles/roads/x=12&y=10&z=4

That means that the Thunderforest and OpenMapSurfer tilelayers no longer work.

I've emailed the uni to see if their addresses have changed and if they're still available, so I'll commit some changes to a PR if I have a positive response.

Best,

**Comment by JasonThomasData** [comment]
Actually, it seems only OpenSurfer is that uni.
No matter I'll contact the others also.

**Comment by jieter** [comment]
Thanks for looking into this, feel free to open a pull request to fix any changed urls.

However, when I look at the [Thunderforest layers](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=Thunder), they seem to work without a problem. OpenMapSurfer seems to be down indeed.

**Comment by jieter** [comment]
@JasonThomasData any news on this? Do we need to take action?

**Comment by brunob** [comment]
@jieter OpenMapSurfer roads is ok, but grayscale version is down since a while... I'll try to contact them to get information asap :)

**Comment by JasonThomasData** [comment]
When I raised the issue I contacted the university behind it but I did not
receive a response. I'm out of town and can try again Monday

**Comment by jieter** [comment]
Any news?

**Comment by brunob** [comment]
Not for now, sorry for the delay, i'll try to get informations next week.

**Comment by JasonThomasData** [comment]
Not from me, they did not respond, sorry.

**Comment by brunob** [comment]
Think we can keep openmapsurfer grayscale since i got this answer from Maxim who works at geog.uni-heidelberg.de : 

> At the moment, some layers on our server are not available due to hardware issues. It is very likely that grayscale tiles will be available next week.

**Comment by jieter** [comment]
So, what action do we need to take on this?

**Comment by brunob** [comment]
OpenMapSurfer roads and grayscale are up, we can close this issue.
