### ISSUE TITLE
HERE and R leaflet - pass App_Id and App_Code through function addProviderTiles

### ISSUE THREAD

**Issue by Tintin07** [leaflet-extras/leaflet-providers#218]
How do I pass the App_Id and App_Code for the basemaps of my HERE account through function addProviderTiles from the R package leaflet?

**Comment by brunob** [comment]
Don't know R leaflet package, but as said in the readme you pass this options on your L.tileLayer.provider() init : https://github.com/leaflet-extras/leaflet-providers#here-formerly-nokia

**Comment by jieter** [comment]
@Tintin07 If you look at the manual for [R leaflet basemaps](https://rstudio.github.io/leaflet/basemaps.html), you'll find you can pass options:

    addProviderTiles("Stamen.TonerLines",
        options = providerTileOptions(opacity = 0.35)
    )
