### ISSUE TITLE
Mapquest will close free access on Monday, July 11, 2016

### ISSUE THREAD

**Issue by brunob** [leaflet-extras/leaflet-providers#219]
Think we can remove these tiles from the project, or add an option to define the dev key...

https://lists.openstreetmap.org/pipermail/talk/2016-June/076106.html

**Comment by jieter** [comment]
I guess we have two options:

1. Register and add an example API key, similar to the current situation with HERE.
2. Remove the [MapQuest](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=MapQuest) layers.

**Comment by brunob** [comment]
Thx @jieter
