### ISSUE TITLE
add lyrk tiles

### ISSUE THREAD

**Issue by brunob** [leaflet-extras/leaflet-providers#228]
I've already seen these nice tiles but i can't find a clear mention about their usage (i'm not a german speaker and automatic translation doesn't help me) : 

https://geodienste.lyrk.de/

OSM wiki state that : 

> specific amount of delivered tiles are for free, more traffic available by paying. retina tiles optional.

@lyrk any thoughts about this ? Could we add lyrk tiles to our project ?

**Comment by maikhoepfel** [comment]
According to http://lyrk.de/, the service was discontinued last year. I discovered them myself because I liked the map style; luckily it's available at https://github.com/lyrk/lyrk-mapstyle. 

I think this ticket can unfortunately be closed.

**Comment by brunob** [comment]
nice catch @maikhoepfel we can close this one :\
