### ISSUE TITLE
Uncaught TypeError: L.tileLayer.provider is not a constructor

### ISSUE THREAD

**Issue by catbadger** [leaflet-extras/leaflet-providers#229]
actual message is L.tileLayer.provider is not a function... I don't know why but none of the plugins work with rc3.

**Comment by catbadger** [comment]
L.tileLayer.provider is not a function

**Comment by catbadger** [comment]
I'm embarassed.

**Comment by jieter** [comment]
Please show us a reproducible example that fails, we'll look if we can fix it.

**Comment by catbadger** [comment]
This was due to my not including the js files properly. FACEPALM.
