### ISSUE TITLE
There's no installation instructions anywhere to be found.

### ISSUE THREAD

**Issue by TianRB** [leaflet-extras/leaflet-providers#234]
Why are there no usage instructions whatsoever? How would someone use this on his/her map?

**Comment by brunob** [comment]
You have to include leaflet-providers.js in your page and you're ready to go :)

Feel free to provide a pull request in order to add a specific part for that in the readme.

**Comment by jieter** [comment]
@TianRB Closing this, if it's still not clear enough, please reopen.
