### ISSUE TITLE
Add Google Maps provider

### ISSUE THREAD

**Issue by ebrensi** [leaflet-extras/leaflet-providers#236]
As  far as I now, the currently best way to use Google maps baselayers in leaflet is via Iván Sánchez' project [GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant).  Would it be too much trouble to include that as a dependency for `leaflet-providers`? 

I will do that when I get time but if someone else feels like doing it first, go ahead!

**Comment by jieter** [comment]
Apart from the implementation, google maps tiles can not be considered free by any stretch of the imagination. Sadly, we will not add it to leaflets providers because of that.

**Comment by ebrensi** [comment]
From leaflet-providers [readme.md](readme.md):

>  What do we mean by free?
> 
> 1 We try to maintain leaflet-providers in such a way that you'll be able to use the layers we include without paying money. This doesn't mean no limits apply, you should always check before using these layers for anything serious.

https://www.ubilabs.net/en/news/google-maps-apis-licensing-2016-04-21

Google maps API is free for developers making free software. The API key is optional and is used for analytics.

**Comment by jieter** [comment]
Alright, but the [TOS](https://developers.google.com/maps/terms) requires the use of the google maps API. Which is indeed another definition of free.

Here are some plugins to use Google maps tiles with Leaflet:

- https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant
- https://github.com/shramov/leaflet-plugins

you can look at their implementation and see that it's not straightforward. At the very least, it requires including more javascript code, which is not really how leaflet-providers works.

**Comment by ebrensi** [comment]
ok.  I'm using both GoogleMutant and leaflet-providers for my project https://github.com/ebrensi/heatflask.  I thought it would be nice to combine the two but no problem.  I see the issue.

**Comment by vincerubinetti** [comment]
Just checking back on this many years later. Does anyone know if the legal status of this has changed?

Some of the tile endpoints seem to be publicly accessible...

https://mt1.google.com/vt/lyrs=s&x=0&y=0&z=0

But of course that doesn't mean you'd be legally allowed to include access to that in an open source project.

Interestingly, Open Layers examples and docs seem to suggest that an API key is required:

https://openlayers.org/en/latest/examples/google.html
https://openlayers.org/en/latest/apidoc/module-ol_source_Google-Google.html

And a Vue wrapper library of Open Layers (much smaller audience) straight up just includes that tile endpoint in one of their examples, without any authentication:

https://openlayers.org/en/latest/apidoc/module-ol_format_filter_Not-Not.html
