### ISSUE TITLE
Unable to scroll list of providers

### ISSUE THREAD

**Issue by alexcroox** [leaflet-extras/leaflet-providers#238]
Having used this tool for a couple of years to experiment with the different tile providers I remember there being a long list on http://leaflet-extras.github.io/leaflet-providers/preview/

Now there isn't enough to scroll the page, or the scroll is broken?

**Comment by brunob** [comment]
> Now there isn't enough to scroll the page, or the scroll is broken?

I have no problem with the scroll, can you share a screenshot and tell us which browser you are using ?

**Comment by alexcroox** [comment]
Chrome Version 55.0.2883.95 (64-bit) OSX 10.11.6

Here is a gif, it seems the scroll wheel action on the list is being passed to the underlying map scroll zoom instead.

Here is a gif of me trying that:

https://cl.ly/iczF/Screen%20Recording%202017-01-04%20at%2009.02%20am.gif

**Comment by brunob** [comment]
With chromium 55.0.2883.87 on ubuntu i can see the scroll bar but i get the same problem when i use the mouse wheel on the layers pane. It may be a leaflet bug, have to search in leaflet issues...

**Comment by thgh** [comment]
Same here on Chrome 55.0.2883.95 (64-bit) on OS X

**Comment by brunob** [comment]
The bug comes from leaflet core, let's wait for 1.0.3 release with hope it will fix this.

**Comment by brunob** [comment]
Preview page is using leaflet 1.0.3 now and the scroll with mouse wheel in control layers is still broken. anyway, it seems to be a leaflet bug and a patch is proposed on Leaflet/Leaflet#5348 so i think we can close this issue. Feel free to comment if you think i should not close it.
