### ISSUE TITLE
Incorrect maxzooms for Thunderforest layers

### ISSUE THREAD

**Issue by gravitystorm** [leaflet-extras/leaflet-providers#239]
https://github.com/leaflet-extras/leaflet-providers/blob/bd34bc81dba2d93c9d042e77ab40c68881d73ab1/leaflet-providers.js#L146-L177

All Thunderforest layers are available from zooms 0 to 22. I'm not sure why some are restricted to 19. I can understand why the Spinal Map layer might be set to 11, but trust me it works to zoom 22!

**Comment by jieter** [comment]
@gravitystorm Feel free to open a PR correcting the values!

**Comment by gravitystorm** [comment]
Thanks!
