### ISSUE TITLE
Website issue: side panel scrolling is broken in Chrome

### ISSUE THREAD

**Issue by rhewitt22** [leaflet-extras/leaflet-providers#248]
When I try to scroll through the list of basemap options the map zooms in/out rather than scrolling.

Viewing on Mac w/Google Chrome Version 56.0.2924.87 (64-bit).
Firefox works as expected.

![scroll-issue](https://cloud.githubusercontent.com/assets/3673374/23318677/6075384a-faa1-11e6-80b3-81e79a3de296.gif)

**Comment by jieter** [comment]
yes, known issue, #238. I think I can fix it in leaflet-providers with 1.0.3 out. I'll update if that helps here.
