### ISSUE TITLE
Leaflet Version 1.3.1?

### ISSUE THREAD

**Issue by schloerke** [leaflet-extras/leaflet-providers#264]
Hello,

I'm wondering if leaflet-providers will work with v1.3.1 of leaflet.  I'm trying to update R's leaflet package to use leaflet 1.3.1.  https://github.com/rstudio/leaflet/pull/492

Currently the dependancies state leaflet version ~v0.7.3.  

Thank you for your help.

Best,
Barret

**Comment by brunob** [comment]
I can confirm it works well with leaflet 1.x, i can't see any occurrence of leaflet in https://github.com/leaflet-extras/leaflet-providers/blob/master/package.json#L27
