### ISSUE TITLE
what about maps.wikimedia.org ?

### ISSUE THREAD

**Issue by Cyrille37** [leaflet-extras/leaflet-providers#265]
Hello,
Is integration of maps.wikimedia.org has already been discuted (I did not found any issue), or should I create a PR for ?

The map: https://maps.wikimedia.org
Terms of Use : https://wikimediafoundation.org/wiki/Maps_Terms_of_Use

Cheers

**Comment by brunob** [comment]
@Cyrille37 nice, feel free to provide a PR for that :)
