### ISSUE TITLE
Customising maps.

### ISSUE THREAD

**Issue by BobbyBabes** [leaflet-extras/leaflet-providers#274]
Are there directions to customise a map ?

I love the CartoDB.DarkMatter and CartoDB.DarkMatterNoLabels maps. But the colours are the opposite of what I was looking for. I was looking for water in black and land in a mid-grey. And without roads and buildings. The maps display very well in my program.

P.S.
I went to the Carto website, but their contact form is geared towards business inquiries. Nothing else.

**Comment by brunob** [comment]
We just provide tiles layers as they are made by their authors/providers, so the short answer is no...
