### ISSUE TITLE
how to have an api key with Thunderforest maps?

### ISSUE THREAD

**Issue by vincent3569** [leaflet-extras/leaflet-providers#275]
hi

could you update your readme.md to describe how to have an api key with Thunderforest maps?

the link to Thunderforest
https://www.thunderforest.com/

**Comment by jieter** [comment]
@vincent3569 since you are into it now, it would be nice if you could provide a Pull Request to change the readme. Just clicking the edit button in this repo should let github handle the forking and opening the pull request for you.

**Comment by vincent3569** [comment]
see https://github.com/leaflet-extras/leaflet-providers/pull/277
