### ISSUE TITLE
Download all tiles from one region

### ISSUE THREAD

**Issue by AppWerft** [leaflet-extras/leaflet-providers#278]
Hi,  

next we have here in Germany and other countries the new internet rule named "General Data Protection Regulation" and it is not allowed to use remote assets.
How can I recursively download tiles?

**Comment by brunob** [comment]
@AppWerft i'm also concerned by RGPD and i don't think i can't use osm tiles or other, have you any reference about what you says ? I think leaflet-providers script have nothing to do with RGPD.

**Comment by brunob** [comment]
+ generally tiles providers doesn't recommand/allow to download tiles massively from their server

I think we can close this issue.

**Comment by AppWerft** [comment]
Thanks for the hint. In my case I only need the tiles for Hamburg. Anyway. I have installed a reverse proxy for nginx. So I can deliver the tiles from my server. ;-)
