### ISSUE TITLE
Stamen TopOSMRelief broken on Retina

### ISSUE THREAD

**Issue by zerocrates** [leaflet-extras/leaflet-providers#283]
See the demo. It appears that there aren't Retina tiles for that style available...

https://stamen-tiles-b.a.ssl.fastly.net/toposm-color-relief/3/2/3@2x.jpg
https://stamen-tiles-b.a.ssl.fastly.net/toposm-color-relief/3/2/3.jpg

This was apparently a problematic tileset before (see #184), and isn't really documented that I can see.

**Comment by zerocrates** [comment]
Watercolor also seems to be problematic, though it's returning a different sort of error...

https://stamen-tiles-b.a.ssl.fastly.net/watercolor/3/1/4@2x.jpg

**Comment by JLuc** [comment]
I confirm the issue : 

Leaflet's url sheme for stamen tiles has changed recently and now features `{r}` = the retina option : 
`url: 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',`

That's fine for some stamen layers, but watercolor doesnt provide any retina tiles (see https://github.com/stamen/maps.stamen.com/issues/56 ) When requested, the map appears empty.

The stamen watercolor provider should be described in such a way that it doesnt requests retina tiles (either with a dedicated option or as a separate provider ?)

Or maybe : it seems  getTileUrl doesnt check detectRetina to compute 'r'. Shouldnt it check it first ?

**Comment by JLuc** [comment]
Yes, adding url: 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}.{ext}',  in watercolor variant fixes the issue.
I proposed https://github.com/leaflet-extras/leaflet-providers/pull/286

(Maybe the same could fix TopOSMRelief ?)
