### ISSUE TITLE
Change protocol relativity note in README.md

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#285]
https is preferred, http is only used if https is not available.

**Comment by brunob** [comment]
I think we can simply ditch all the `Protocol relativity (https://-urls)` part (?)

**Comment by jieter** [comment]
I think so too

**Comment by brunob** [comment]
Here we go, going to try to push a new release for the geoportail folks ;)

**Comment by brunob** [comment]
Got it, `uglify-js` not `uglifyjs`, sorry for the noise :p

**Comment by brunob** [comment]
Ooops, publised a minor instead a patch :\

**Comment by jieter** [comment]
👍
