### ISSUE TITLE
Isn't this plugin breaking several TOS?

### ISSUE THREAD

**Issue by tgelz** [leaflet-extras/leaflet-providers#288]
I was looking for new tile servers to add to our application, when I came across this plugin. To my surprise, I found several providers built into the plugin that I had previously decided against using, due to incompatible TOS. Please correct me if I'm wrong.

**ESRI**:
Requires dynamic attribution based on pan/zoom for most of the tiles (e.g. https://static.arcgis.com/attribution/World_Street_Map)

**HERE**:
Same as above (https://developer.here.com/documentation/map-tile/topics/resource-copyright.html)

**OpenMapSurfer**:
Requires permission when not used through their website (http://korona.geog.uni-heidelberg.de/contact.html#useterms)

**Comment by brunob** [comment]
I think your wrong ;)

I personally had contact with openmasurfer team and they allowed us to provide access to their tiles, that's what we do for every new tile provider that doesn't state clearly an open use of their tiles.

For ESRI & HERE, i let @jieter clarify the situation.

**Comment by jieter** [comment]
I've had some email exchanges with HERE, never have they mentioned attribution as a problem.

Concerning ESRI, please refer to [this comment](https://github.com/leaflet-extras/leaflet-providers/issues/22#issuecomment-27988254). The complete thread might be of interest though.

@tgelz I'm closing this for now, if you still have issues about TOS violation, please reopen.
