### ISSUE TITLE
GeoportailFrance tiles doesn't work with my apikey

### ISSUE THREAD

**Issue by vincent3569** [leaflet-extras/leaflet-providers#290]
hi

as required, I registred on http://professionnels.ign.fr/ign/contrats/ to have a personnal apikey.
but as far I can see, I can't make it works for all GeoportailFrance resources.

if I use `L.tileLayer.provider('GeoportailFrance.orthos').addTo(map);` it works well
but if I use `L.tileLayer.provider('GeoportailFrance.orthos', {apikey: 'my_apikey'});` or `L.tileLayer.provider('GeoportailFrance', {variant: 'ORTHOIMAGERY.ORTHOPHOTOS', apikey: 'my_apikey'});` it doesn't work.

you can have a look here: https://test.vincentbourganel.fr/test_osm_map.html

**Comment by vincent3569** [comment]
ok, it's for me
my apikey wasn't defined with the good http referer, so it doesn't work on my website.
now it works fine with `L.tileLayer.provider('GeoportailFrance', {variant: 'ORTHOIMAGERY.ORTHOPHOTOS', apikey: 'my_apikey'});`

**Comment by vincent3569** [comment]
but now, as far I can see, with my right apikey, GeoportailFrance.parcels tiles doesn't work with overlayLayers as following:

````
	<script>
		var map = L.map('osm_map', {
                    zoomControl: false,
                    zoom: 4,
                    minZoom: 2
                });
		var defaultLayer = L.tileLayer.provider('GeoportailFrance.orthos').addTo(map);
		var baseLayers = {
            'OpenTopoMap': L.tileLayer.provider('OpenTopoMap'),
            'GeoportailFrance.orthos ok': defaultLayer,
            'GeoportailFrance.ignMaps ok': L.tileLayer.provider('GeoportailFrance.ignMaps'),
            'GeoportailFrance.maps ok': L.tileLayer.provider('GeoportailFrance.maps'),
        };
        var overlayLayers = {
            'GeoportailFrance.parcels ok': L.tileLayer.provider('GeoportailFrance.parcels'),
            'GeoportailFrance.parcels ko': L.tileLayer.provider('GeoportailFrance', {variant: 'CADASTRALPARCELS.PARCELS', apikey: 'my_apikey'}),
        }
		L.control.zoom({position: 'topleft'}).addTo(map);
		L.control.layers(baseLayers, overlayLayers, {position: 'topright'}).addTo(map);
		L.marker([44.000,2.000]).addTo(map);
		L.marker([46.000,4.000]).addTo(map);
		map.fitBounds([
			[43.000,2.000], [47.000,4.000]
		]);
	</script>
````

you can see the code in action here: http://test.vincentbourganel.fr/test_osm_map.html

**Comment by jieter** [comment]
Please narrow it down to the minimal example, which boils down to this:
```
'GeoportailFrance.parcels ok': L.tileLayer.provider('GeoportailFrance.parcels'),
'GeoportailFrance.parcels ko': L.tileLayer.provider('GeoportailFrance', {variant: 'CADASTRALPARCELS.PARCELS', apikey: 'my_apikey'}),
```
Your second call should look like this:
```
'GeoportailFrance.parcels ko': L.tileLayer.provider('GeoportailFrance.parcels', {apikey: 'my_apikey'}),
```
The reason  your version doesn't work is that `GeoportailFrance` has 'image/jpeg' tiles by default, but the 'parcels' tiles are 'image/png'. Your second definition changes the layer argument of the url, but not the format argument.

You should have been able to see errors in your browser console, maybe even with proper error messages in the response.

Anyway, I don't see a leaflet-providers bug here.

**Comment by vincent3569** [comment]
hi
thanks for explanations. now it works well.
