### ISSUE TITLE
How to clear old map layers with leaflet providers

### ISSUE THREAD

**Issue by kgrosvenor** [leaflet-extras/leaflet-providers#291]

**Comment by brunob** [comment]
Could you be "a bit" more specific in your question ?

**Comment by kgrosvenor** [comment]
If you dynamically switch your layers and  when you pan the map, there is still old map tiles cached below the new tiles loading in

**Comment by matkoniecz** [comment]
Have you tested whatever it is specific to this leaflet extension?

**Comment by jieter** [comment]
All this plugin does is return instances of `L.TileLayer`. I think you are experiencing Leaflet behaviour, so please report any issues (with proper explanation and maybe an example demonstrating your issue) over there.
