### ISSUE TITLE
Not all HERE maptiles available

### ISSUE THREAD

**Issue by jayyx2** [leaflet-extras/leaflet-providers#293]
I found that not all the HERE maptiles were available. I modified the JS to include them and it seems to work as expected. Reduced.day, Reduced.night, and a couple others.

[leaflet-providers.js.txt](https://github.com/leaflet-extras/leaflet-providers/files/2291631/leaflet-providers.js.txt)

**Comment by jayyx2** [comment]
Done, sorry would've done it initially but am a noob on using Github

**Comment by brunob** [comment]
No problem & thx for the pull request :)

**Comment by jieter** [comment]
fixed by #294
