### ISSUE TITLE
Typos in HERE variant names

### ISSUE THREAD

**Issue by Toutouwai** [leaflet-extras/leaflet-providers#304]
Typos [here](https://github.com/leaflet-extras/leaflet-providers/blob/36b6eddaedeb2bcd3a015e11630a502ae5ad6465/leaflet-providers.js#L471-L472):

```js
redcuedDay: 'reduced.day',
redcuedNight: 'reduced.night',
```

**Comment by brunob** [comment]
Done, i think it's time to push a new release.

**Comment by brunob** [comment]
@jieter wait a bit, i think we can also fix some thing for cartodb tiles... (PR coming)
