### ISSUE TITLE
Too slow at the first load

### ISSUE THREAD

**Issue by Kianoosh76** [leaflet-extras/leaflet-providers#308]
Hi! Thanks for your wonderful map, the only problem there is that in the very first load, it takes too much time to load the map and since it's an inline js, nothing is shown on the web page while loading the map! This may affect the users' experience!

**Comment by jieter** [comment]
How would you propose to fix this? I think the target use of this line is not really in simple map views in news articles, but rather data exploration platforms.

**Comment by Kianoosh76** [comment]
So at least it might be better to release a lighter version (if possible) for ordinary usage, cause since Google Maps is no longer free, every developer needs an alternative one badly!
