### ISSUE TITLE
OpenStreetMap Black and white style is down

### ISSUE THREAD

**Issue by opineus** [leaflet-extras/leaflet-providers#316]
Hi, 
It looks like that the OpenStreetMap.BlackAndWhite style map could not be loaded.

https://leaflet-extras.github.io/leaflet-providers/preview/
The server is responding with a status of 404.

Could you please investigate. 
Thanks,
Ivan

**Comment by brunob** [comment]
The problem comes from a outdated ssl certificate as said here : https://help.openstreetmap.org/questions/68243/osm-black-and-white-https-err_cert_common_name_invalid

But it seems that the tiles were simply removed from server after that : 

> EDIT: Wikimedia have now removed these old tiles completely.

Think that we have to remove this provider from leaflet-providers. Any thoughts @jieter ?

**Comment by jieter** [comment]
Yes, should be removed.

**Comment by pandubalraj** [comment]
@jieter is there any alternative for black and white mapnik that you would recommend

**Comment by brunob** [comment]
@pandubalraj http://leaflet-extras.github.io/leaflet-providers/preview/#filter=CartoDB.Positron should do the job ;)

**Comment by brunob** [comment]
More info here https://phabricator.wikimedia.org/T204506#5031693

> Yes, as you may note from this ticket, this service has been mostly running unmaintained since 2015 (many tiles were not refreshed since date as well... ). As we are going through several large changes in our cloud platform these services needed migration. Over the past 3 months, as a volunteer, I've taken on the job of getting familiar with this service and starting to rebuild this service. This might lead to reduced availability of maps in the short term as I deal with several large problems in the little time I have available to work on this. It is my intent that hikebike, osm-bw and osm-no-labels are retained in the long run.

**Comment by pandubalraj** [comment]
Thanks for the update. Hopefully waiting for osm bw to run.
It will be very thankful if we know the ETA
Thanks
