### ISSUE TITLE
Add KOMPASS hiking maps

### ISSUE THREAD

**Issue by adrfantini** [leaflet-extras/leaflet-providers#321]
I have played a bit with `leaflet` and tested different providers. For hiking in Europe, the best free basemap is still the one provided by KOMPASS and used [here](https://www.kompass.de/wanderkarte/tour-planen/), see this issue for more info: https://github.com/rstudio/leaflet/issues/543

Maybe you could add it to the provider list?

**Comment by brunob** [comment]
I can't find any tiles usage policy on their site, but "i'm not sure" we can use expose their tiles in leaflet-providers...

**Comment by adrfantini** [comment]
Not sure either. Some info might be here but I do not speak German unfortunately:
https://www.kompass.de/service/datenschutz/

**Comment by brunob** [comment]
This page is more appropriate https://www.kompass.de/service/agb/ anyway, theses tiles are not openly usable, think we can close the issue. Feel free to contact kompass team to ask about it, and reopen the issue if you got a positive answer ;)
