### ISSUE TITLE
Maptiler Cloud provider

### ISSUE THREAD

**Issue by answerquest** [leaflet-extras/leaflet-providers#327]
Feature request: Include Maptiler Cloud. (https://www.maptiler.com/cloud/)
Very similar to the mapbox tile sources

Path for raster 256x256 tiles:
`https://api.maptiler.com/maps/{style}/256/{z}/{x}/{y}.png?key={apikey}`

style values: `basic, bright, darkmatter, hybrid, pastel, positron, streets, topo, topographique, voyager`

**Comment by brunob** [comment]
Hi and thx for the hint, feel free to provide a PR for that :)
