### ISSUE TITLE
Swatch/previews out of alignment with main map

### ISSUE THREAD

**Issue by DaveF63** [leaflet-extras/leaflet-providers#328]
Hi
Most of the swatch previews are out of alignment with the main map. Is it possible to recalibrate them?

Also, why do some previews which aren't greyed out have a greyed out radio button?

**Comment by brunob** [comment]
> Most of the swatch previews are out of alignment with the main map. Is it possible to recalibrate them?

I don't understand or don't see the bug, can you provide a screenshot and explain it a bit ?

> Also, why do some previews which aren't greyed out have a greyed out radio button?

Certainly because the map is out of bound or zoom level for these tiles/overlays.

**Comment by DaveF63** [comment]
Thanks for the prompt reply.

It's hard to replicate as it resets itself to show them correctly if panning &/or zooming.
However I managed to screengrab an example:
Buckingham Palace with unaligned previews. This is the centre of the previews: https://osm.org/go/euu4OgE85-?m=

![Leaflet Render offset swatch](https://user-images.githubusercontent.com/9528328/61812889-5fcc3500-ae3c-11e9-8998-479994bfafe1.JPG)

Same view with correctly aligned previews:

![Leaflet Render correct swatch](https://user-images.githubusercontent.com/9528328/61813169-f993e200-ae3c-11e9-9e3f-84a2b26bfcfd.JPG)

**Comment by brunob** [comment]
Which browser are you using ? Does the bug show if you load http://leaflet-extras.github.io/leaflet-providers/preview/ and don't pan or zoom ?

**Comment by DaveF63** [comment]
Firefox (on auto update)
Displays correctly.

Just tried it on Chrome & after panning & zooming would say it's worse, with the preview even further out of alignment.

**Comment by brunob** [comment]
Can't reproduce it with chromium 74.0.3729.169...

**Comment by brunob** [comment]
Which link are you talking about ?

**Comment by DaveF63** [comment]
Sorry, I though I sent you a link, but it doesn't matter it's the same problem anywhere. 
Both browsers are 64bit.

**Comment by jieter** [comment]
Note that this layers control is not developed as part of this repository, but in jieter/leaflet.layerscontrol-minimap. If you have a reliable way of reproducing the issue, please open an issue / PR there.

**Comment by DaveF63** [comment]
@jieter 
Update: It only occurs when using mouse keys to pan. The keyboard arrow keys pan as expected. To get the swatches to realign to the correct view either the mouse zoom wheel or +/- keys can be used.

It's still "reliably" occurring. As you're the creator & therefore aware of it, you can transfer it to your github site where you can look into the problem.
