### ISSUE TITLE
Add CyclOSM

### ISSUE THREAD

**Issue by Florimondable** [leaflet-extras/leaflet-providers#334]
Hi, can you add the map CyclOSM from https://www.cyclosm.org ?
It's a free cycle map, much more uptodate than opencyclemap.

Tiles url https://dev.{s}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png

Project https://github.com/cyclosm/cyclosm-cartocss-style/

**Comment by brunob** [comment]
Fixed by #335 :)
