### ISSUE TITLE
TypeError: L.tileLayer.provider is not a function. 

### ISSUE THREAD

**Issue by phpmods** [leaflet-extras/leaflet-providers#337]
Unfortunately, whenever I try to load the map on my website I get the following error.
TypeError: L.tileLayer.provider is not a function. (In 'L.tileLayer.provider(opts.provider)', 'L.tileLayer.provider' is undefined)
The website is this: http://va.hkrscoc.com/index.php/acars and the map is not loading right.

**Comment by brunob** [comment]
Dont't know what you are trying to achieve but i see 4 occurrences of leaflet.js in you page and 2 occurrences of leaflet-providers.js + the fact that your page throw 2 errors which could be the source of your problem. Fix all theses mistakes, and we may be able to help you.

**Comment by brunob** [comment]
No news about this, closing.
