### ISSUE TITLE
nlmaps.luchtfoto is broken

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet-providers#338]
http://leaflet-extras.github.io/leaflet-providers/preview/#filter=nlmaps.luchtfoto

shows bit.ly/pdok-services which in turn point to https://www.pdok.nl/datasets.

**Comment by brunob** [comment]
Maybe a hint here https://www.pdok.nl/-/pdok-geodatastore-volledig-uit-productie but i don't read nl.

Should we remove this layer ?

**Comment by jieter** [comment]
I merely added the issue to remind myself, I'll look into it.
