### ISSUE TITLE
Use HERE apiKey v3 instead of legacy app_id and app_code

### ISSUE THREAD

**Issue by mcguffin** [leaflet-extras/leaflet-providers#342]
I cannot generate an `app_id` / `app_code` pair in my (freshly generated) HERE account any more, they seem to have switched to a single apiKey authorization. 
https://developer.here.com/documentation/map-tile/dev_guide/topics/quick-start-map-tile.html

I would gladly craft a PR to fix this, but I am not sure, if `*.maps.api.here.com` with `app_id` and `app_code` is still functional. Does anyone have more intel on this?

**Comment by brunob** [comment]
Thx for the PR proposition :)

Sorry, i don't have any info about here usage from my side...

**Comment by mcguffin** [comment]
I just asked in HEREs slack channel. Lets hope they have answers...

**Comment by mcguffin** [comment]
No answer from HER yet ... anyway, some people on slack still seem to use app_id and app_code, so I posted a non-destructive PR.
