### ISSUE TITLE
Migrating to the modern Static Tiles API

### ISSUE THREAD

**Issue by stell** [leaflet-extras/leaflet-providers#349]
Just got informed:
https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/

Would there be a problem because of the 512x512 tile size ?

**Comment by ebrensi** [comment]
@stell there is a Leaflet issue about that https://github.com/Leaflet/Leaflet/issues/4391.
Apparently it was solved by setting `zoomOffset: -1`, and they closed it. 

When I get a chance I will try it myself and make a pull request if it works, unless you are already on it.
