### ISSUE TITLE
"WMFLabs.OSM Black and White" don't work on demo page

### ISSUE THREAD

**Issue by k-dmitrii** [leaflet-extras/leaflet-providers#350]
on this page https://tools.wmflabs.org/maplayers-demo/

**Comment by brunob** [comment]
See #316

**Comment by k-dmitrii** [comment]
but this is not because of "{s}." and "mapnik2" in url?
var WMFLabs_OSM Black and White = L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik2/{z}/{x}/{y}.png'
this one still works https://tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png

**Comment by brunob** [comment]
@k-dmitrii i see that it seems to work again here https://phabricator.wikimedia.org/T204506#5075223

I've tested it and it's ok, feel free to provide a PR for that :)

**Comment by k-dmitrii** [comment]
hm. "{s}.tiles.wmflabs.org" redirect to "tiles.wmflabs.org" it's ok, but "mapnik2" still in url at demo
work https://a.tiles.wmflabs.org/bw-mapnik/0/0/0.png
don't work https://a.tiles.wmflabs.org/bw-mapnik2/0/0/0.png

**Comment by brunob** [comment]
i know, that's why i ask for a PR, since those tiles were removed since #316.
