### ISSUE TITLE
OpenStreetMap Sweden is down

### ISSUE THREAD

**Issue by karlwettin** [leaflet-extras/leaflet-providers#351]
The OpenStreetMap Sweden is down due to hardware failure.

This means that the Hydda layers, also used by Leaflet providers as the base for transparent layers, is not functioning.

It might take several weeks until we get the server back online. We're in contact with sponsors to help out with new disks. In worst case we're unable to salvage the old data and have to reinstall the server from scratch. The tile server is a secondary service we provide for the mapping community, so we might not be able to prioritize that the most.

Sorry for this. We will report back to you in this issue when we have more information.

Karl
OSM SE

**Comment by karlwettin** [comment]
Also see [carto style project issue](https://github.com/karlwettin/carto-style-hydda/issues/3) regarding this.

**Comment by brunob** [comment]
> Sorry for this. We will report back to you in this issue when we have more information.

@karlwettin you don't have to be sorry, thx for pinging us and we wish you the best and good luck for solving this issue :)

**Comment by brunob** [comment]
@jieter it's been almost 2 years than these tiles are unavailable, what do you think about removing them from the script ?

**Comment by karlwettin** [comment]
I'm the author of the map style. The OSM SE server seems to be down for quite a while. I've been working on a new version of the style, and it's being hosted on my private server. The underlying database is static and more than a year old. At some point this was planned to become a paid for subscription service with limited free usage (compare most commercial services). Would that fit here?

The main focus of the work has been to evenly distribute location names, so that things show up even in sparsely populated areas. For instance, compare locations available in:

Bretagne France:
https://tiles.musa.kodapan.se/compare.html#48.10376,-2.87567,8z
Iceland:
https://tiles.musa.kodapan.se/compare.html#65.14611,-18.46802,6z
Northern Fennoscandia:
https://tiles.musa.kodapan.se/compare.html#69.52683,22.22534,6z

There is also multi language layer support with transliteration of non latin names. 

International layer:
https://tiles.musa.kodapan.se/?lang=int#25.02588,98.55835,6z
Swedish layer with transliterations:
https://tiles.musa.kodapan.se/?lang=sv#25.02588,98.55835,6z
English layer with no transliterations:
https://tiles.musa.kodapan.se/?lang=en#25.02588,98.55835,6z

There's also more data about forestry, deserts, cultivated land etc on low zooms:
The Nile delta:
https://tiles.musa.kodapan.se/compare.html#30.3634,30.92102,7z
Borealian forrest in Scandinavia:
https://tiles.musa.kodapan.se/compare.html#63.99524,22.96143,5z

**Comment by brunob** [comment]
Nice to get news about hydda, thx @karlwettin :)

> Bretagne France:

Good choice, even if i'm not very objective on the subject :p

Anyway, since tiles are hosted on a personal server, i don't think it would be fair from us if we put this in the script, since it can drain a lot of traffic to your server.

**Comment by jieter** [comment]
> @jieter it's been almost 2 years than these tiles are unavailable, what do you think about removing them from the script ?

Yes, let's remove them.

**Comment by brunob** [comment]
@jieter done, sorry i've forgot to make a PR :\

**Comment by brunob** [comment]
Also made a cleanup to hydda references, there is still one reference in https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/vendor/L.Control.Layers.Minimap.js#L18 but this concern another repo.
