### ISSUE TITLE
Providing User-Agent for using maps.wikimedia.org

### ISSUE THREAD

**Issue by philgyford** [leaflet-extras/leaflet-providers#353]
In #265 the ability to maps.wikimedia.org was added. Maybe since then the Terms of Use have changed, but they now say:

> If you are developing an application that uses the Wikimedia Maps service, you must provide a valid HTTP User-Agent that includes your application, version, and sufficient information to easily contact you (e.g., your email address).
>
> The following are prohibited on the Wikimedia Maps service:
> 
> 1. Excessive downloading (such as downloading significant areas of tiles for later offline usage)
> 2. Accessing the service without a proper HTTP User-Agent or HTTP referer
> 3. Using the service without compliance with any license or copyright terms

I may have missed something obvious, but I can't see a way to specify a user-agent when adding a tile layer.

**Comment by brunob** [comment]
Doesn't seems related to this project, since the tiles are downloaded by the clients, closing feel free to comment if you need.
