### ISSUE TITLE
Map not showing on mobile. Do I need to register for an API?

### ISSUE THREAD

**Issue by yansusanto** [leaflet-extras/leaflet-providers#360]
Is it a common occurrence that the map, while it display properly on desktop, doesn't show on mobile? I'm using the Stadia.AlidadeSmooth layer.

```
L.tileLayer.provider('Stadia.AlidadeSmooth').addTo(map);
```

**Comment by brunob** [comment]
Are you using an API key registred to your domain as required by stadia api ?

> everything should work seamlessly as long as you have an active plan for your domain.
ref https://docs.stadiamaps.com/raster/#displaying-a-map-leaflet

**Comment by yansusanto** [comment]
No, I'm not using an API. Do I need to? And if I need an API, why is it working fine with desktop without an API? Thanks for the response, @brunob

**Comment by brunob** [comment]
> Do I need to? 

Yes, as described in the stadia docs.

> And if I need an API, why is it working fine with desktop without an API?

Because the stadia api seems to allow use on localhost or something like that.

**Comment by brunob** [comment]
No news, closing.
