### ISSUE TITLE
Inaccurate example Mapbox ID in README

### ISSUE THREAD

**Issue by philgyford** [leaflet-extras/leaflet-providers#364]
In the README, under "Mabox" it says:

> You can get map_ID (i.e mapbox.satellite)...

But I think this format ("mapbox.satellite") is inaccurate since [the change to the modern Static Tiles API](https://github.com/leaflet-extras/leaflet-providers/issues/349).

The currently-available Mapbox styles are [listed here](https://docs.mapbox.com/api/maps/#mapbox-styles) and so the possible current strings to use as the `id` with leaflet-providers are:

* "mapbox/streets-v11"
* "mapbox/outdoors-v11"
* "mapbox/light-v10"
* "mapbox/dark-v10"
* "mapbox/satellite-v9"
* "mapbox/satellite-streets-v11"

So – they now use a slash rather than a period, and have version numbers appended.

**Comment by brunob** [comment]
Feel free to provide a PR for that :)
