### ISSUE TITLE
Stamen terrain-background max zoom

### ISSUE THREAD

**Issue by vpipkt** [leaflet-extras/leaflet-providers#368]
It appears that the max zoom is 11 for the Stamen terrain-background variant. Unsure how to verify this.

https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js#L348

**Comment by brunob** [comment]
i don't think so... http://maps.stamen.com/terrain/#17/48.38355/-4.49551

**Comment by vpipkt** [comment]
@brunob I am specifically highlighting the `terrain-background` variant. With that specific variant I get some 404s and some 200s at zoom levels less than the max zoom given. Is there a reference from stamen about the max zoom ? 

    curl -i  http://tile.stamen.com/terrain-background/14/4499/6312.png

**Comment by brunob** [comment]
I can get these tiles too zoom 15 here http://maps.stamen.com/terrain-background/#15/48.3835/-4.4955

FTR, terrain background was introduced by #50 & terrain worldwide by #223 and here is a stamen file reporting zoom range http://maps.stamen.com/js/tile.stamen.js

I think the bug come from stamen tile server cache which may be a bit broken. Maybe you can contact theme to confirm this ?

**Comment by vpipkt** [comment]
@brunob thank you for the research and background info! Closing this.
