### ISSUE TITLE
Is it possible to add cities names in watercolor layer ?

### ISSUE THREAD

**Issue by corentin-branquet** [leaflet-extras/leaflet-providers#371]
Hi ! 

I want to use watercolor layer for my map. But there's no cities indicated.

How can I add cities in watercolor layer ? Or at least display cities that I want to make appear, not with a marker but with their name

Thanks for your reply !

**Comment by brunob** [comment]
Just use two layers for that, and this is not related to the code of this plugin but more about which tiles you want to use, closing.

**Comment by corentin-branquet** [comment]
Ok I got it, I never really know that you can add multiple layers !

Ahah indeed west coast rpz

**Comment by braxtondiggs** [comment]
Are there any pre-built layers that have these kinds of (city) labels?
