### ISSUE TITLE
OpenAIP

### ISSUE THREAD

**Issue by scls19fr** [leaflet-extras/leaflet-providers#372]
Hello,

Adding [OpenAIP tiles](https://www.openaip.net/) sould probably be considered.

See maps https://maps.openaip.net/

See usage https://github.com/hankhank10/MSFS2020-cockpit-companion/blob/5ee36a84408aded2fa8e5e9c5b13df95a11f1a39/templates/glass.html#L512-L520

Kind regards

**Comment by brunob** [comment]
Would you send a PR for that ?

**Comment by scls19fr** [comment]
PR #374 sent  but it doesn't pass unit tests
