### ISSUE TITLE
Remove tile providers that aren't functioning, aren't supported, go against Terms of Service, etc.

### ISSUE THREAD

**Issue by jayyx2** [leaflet-extras/leaflet-providers#380]
Wikimedia is one example. They updated their terms of use, and it also no longer works within the demo https://meta.wikimedia.org/wiki/Revised_Maps_Terms_of_Use_(March_2021)

"The following are prohibited on the Wikimedia Maps service:

Use for anything other than supporting the Wikimedia projects (for example, you may build a tool for Wikipedia editors, but you may not use it for an unrelated app or business)
Excessive downloading (such as downloading significant areas of tiles for later offline usage)
Accessing the service without a proper HTTP User-Agent or HTTP referer
Using the service without compliance with any license or copyright terms"

**Comment by brunob** [comment]
thx for the info, could you provide a PR for that ?
