### ISSUE TITLE
nlmaps.luchtfoto phased out 

### ISSUE THREAD

**Issue by martinfleis** [leaflet-extras/leaflet-providers#387]
`nlmaps.luchtfoto` is not available anymore and the provider migrated to WMS, so there's no replacement URL -
https://www.pdok.nl/-/nieuw-luchtfoto-2020-nu-beschikbaar-bij-pdok

**Comment by brunob** [comment]
Hi and thx for the report, i can read that `nlmaps.luchtfoto` is only depreciated on TMS scheme, but still available on WMTS which is the one we are using. But we should switch from `2018_ortho25` to `Actueel_ortho25` in order to get the latest set of imagery.
