### ISSUE TITLE
NASAGIBS.ModisTerraSnowCover probably broken

### ISSUE THREAD

**Issue by martinfleis** [leaflet-extras/leaflet-providers#389]
I wasn't able to make `NASAGIBS.ModisTerraSnowCover` work in any context so I am not sure if it is still available. I have not found any information on GIBS about that so I am flagging it out as a potentially broken source. It doesn't work in preview and I wasn't able to fetch its tiles directly in the same way as other NASAGIBS sources  (error 400).

**Comment by brunob** [comment]
After an hour of search on the nasa websites, i think i finally found the info on... github :p

https://github.com/nasa-gibs/worldview/issues/1037

`MODIS_Terra_Snow_Cover` => `MODIS_Terra_NDSI_Snow_Cover` seems to fix this layer, PR is on the way.
