### ISSUE TITLE
Fix docs URL for AzureMaps

### ISSUE THREAD

**Issue by kopytjuk** [leaflet-extras/leaflet-providers#427]
The old link to Microsoft docs in [code](https://github.com/leaflet-extras/leaflet-providers/blob/8895d76b4e3a919f0d7239151061b3f389e4d41a/leaflet-providers.js#L1056) is outdated. New URL is now: https://docs.microsoft.com/en-us/rest/api/maps/render-v2/get-map-tile

**Comment by brunob** [comment]
@kopytjuk could you provide a PR for that ?

**Comment by brunob** [comment]
Thx for the PR :)
