### ISSUE TITLE
Question with Esri Licensing

### ISSUE THREAD

**Issue by aswinanbalagan** [leaflet-extras/leaflet-providers#446]
Hi,
In the README file, you write: “In order to use ArcGIS maps, you must register and abide by the terms of service. No special syntax is required.”, but with your plugin, there’s no way for Esri to verify that you’re actually registered (such as by sending an API key or authentication token).

Is Esri asking us to register on the honor system or is it free to use with proper attribution?

**Comment by bsalak** [comment]
I was wondering about that, too. Since today I found out that 
```leaflet() %>% addProviderTiles(providers$Esri.WorldImagery)```
doesn't work anymore when working with RStudio and updated package(s).

**Comment by brunob** [comment]
In fact this one is a dupplicate of #204.
