### ISSUE TITLE
Esri.OceanBasemap not displaying

### ISSUE THREAD

**Issue by hansenjohnson** [leaflet-extras/leaflet-providers#493]
I noticed that the map from Esri.OceanBasemap is not displaying (see provider demo page [here](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.OceanBasemap)). Perhaps it's due to Esri moving from an [old](https://www.arcgis.com/home/item.html?id=5ae9e138a17842688b0b79283a4353f6) to a [new](https://www.arcgis.com/home/item.html?id=67ab7f7c535c4687b6518e6d2343e8a2) OceanBasemap? I was able to get around this issue by manually specifying the path to the new version of the [basemap](https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/) and [reference layer](https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Reference/MapServer/).

**Comment by brunob** [comment]
From my side tiles are loaded on the demo page right now. Do you confirm ?

**Comment by martinfleis** [comment]
It is not working for me either and a [downstream CI](https://github.com/geopandas/xyzservices/actions/runs/4011295197/jobs/6962668225) is also failing, with error 500.

**Comment by brunob** [comment]
Demo page is calling https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/7/44/59

```
curl -LI https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/7/44/59
HTTP/1.1 200 OK
Server: Apache
ETag: "2cs30m4psb2"
Access-Control-Allow-Origin: *
Content-Length: 9868
X-Robots-Tag: noindex
Content-Type: image/jpeg
Date: Tue, 31 Jan 2023 13:03:23 GMT
Connection: keep-alive
Cache-Control: max-age=86400
```

Did you test with one IP or multiple ? Maybe your IP si blocked due to traffic limit from esri ?

**Comment by martinfleis** [comment]
```
curl -LI https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/7/44/59
HTTP/1.1 404 Not Found
Content-Type: text/html;charset=utf-8
Content-Length: 614
Connection: keep-alive
Date: Tue, 31 Jan 2023 13:07:56 GMT
Server: 
Access-Control-Allow-Origin: *
X-Robots-Tag: noindex
X-Cache: Error from cloudfront
Via: 1.1 3bf3e75bcb9a86b3eb343a1d4392a6de.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: FRA2-C1
X-Amz-Cf-Id: c1AtxwuoUlZ474098bsvNNJ9r8JVQZk9dIivNrau0S897OBqZkY6Iw==
```
This is from my local laptop, same with and without VPN. The same response from another machine elsewhere (via ssh). The CI that is failing in xyzservices is running on GHA, so completely detached from that. May it be that it is cached on your side?

**Comment by brunob** [comment]
'k got the 404 after testing from three different IPs.

This patch should do the trick :

```diff
diff --git a/leaflet-providers.js b/leaflet-providers.js
index a7ef138..47b9259 100644
--- a/leaflet-providers.js
+++ b/leaflet-providers.js
@@ -469,7 +469,7 @@
 				},
 				OceanBasemap: {
 					options: {
-						variant: 'Ocean_Basemap',
+						variant: 'Ocean/World_Ocean_Base',
 						maxZoom: 13,
 						attribution: '{attribution.Esri} &mdash; Sources: GEBCO, NOAA, CHS, OSU, UNH, CSUMB, National Geographic, DeLorme, NAVTEQ, and Esri'
 					}
```

PR is on the way.
