### ISSUE TITLE
OpenTopoMap not displaying 

### ISSUE THREAD

**Issue by oufmilo** [leaflet-extras/leaflet-providers#497]
Hello,

I'm using OpenTopoMap for my website and it doesn't work since few days.

https://leaflet-extras.github.io/leaflet-providers/preview/#filter=OpenTopoMap

**Comment by brunob** [comment]
It seems that their website is down http://opentopomap.org/

Wait some days and we'll see if it's getting back.

**Comment by oufmilo** [comment]
It's back ! Thanks !
