### ISSUE TITLE
India map is not correct

### ISSUE THREAD

**Issue by shriprasad15** [leaflet-extras/leaflet-providers#514]
The india maps provided in this link is not correct.
Google for india maps, and you can find the norhern-region(Jammu Kashmir and Ladakh) to be in different styles.

Please provide a.correct map or rectify this issue

**Comment by brunob** [comment]
Could you explain what is the problem please ? We are not responsible of the content of the maps, you should report the problem to the provider of the mentioned tiles.

**Comment by martinfleis** [comment]
I believe this is a question of Kashmir, which is a disputed territory. India requires its area to be shown as a part of India while that is not necessarily accepted boundary between India, Pakistan and China by other countries (notably not by those mentioned). Google maps under an Indian domain show the boundaries according to Indian point of view while google maps under Europeans domain don't. Not sure about US, I suppose it will look like in EU.

**Comment by brunob** [comment]
So we can close here.
