### ISSUE TITLE
Esri.DeLorme returning 404

### ISSUE THREAD

**Issue by martinfleis** [leaflet-extras/leaflet-providers#548]
Esri.DeLorme does not seem to work on the current link any longer. Both https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.DeLorme and downstream CI in xyzservices return 404. From a quick search, I haven't found any reason why so it may have just moved. Who knows...

**Comment by brunob** [comment]
https://www.arcgis.com/home/item.html?id=5e2a5360f91e449b8b61ccdef1ebcc6d only show that the item has been updated on Feb 8

After a bit of search, https://support.esri.com/en-us/products/arcgis-location-services/basemaps-life-cycle state taht "DeLorme World Base Map" have been retired on December 2023 and that it should be replaced by World Streets https://www.arcgis.com/home/item.html?id=55ebf90799fa4a3fa57562700a68c405 which is a vector tileset.

I think we should remove Esri.DeLorme.
