### ISSUE TITLE
add topOsm and USGA layers

### ISSUE THREAD

**Issue by calvinmetcalf** [leaflet-extras/leaflet-providers#58]
per #16 add toposm and the usga layers.

**Comment by jieter** [comment]
USGA is about golf, did you mean USGS?

**Comment by brunob** [comment]
I think so : https://github.com/leaflet-extras/leaflet-providers/issues/16#issuecomment-13992842

**Comment by jieter** [comment]
[TopOSM is already in Stamen provider](http://leaflet-extras.github.io/leaflet-providers/preview/#filter=TopOSM). What kind of layers would you like to include from USGS?

**Comment by brunob** [comment]
No news about this one, closing...
