### ISSUE TITLE
New osm based tiles

### ISSUE THREAD

**Issue by brunob** [leaflet-extras/leaflet-providers#96]
Hi @leaflet-extras/owners i was talking with @kodapan about the nice tiles available on http://openstreetmap.se/tjanster

These tiles are based on osm data and this styles : https://github.com/karlwettin/tilemill-style-hydda

@kodapan (author of the styles and admin of the server) is ok if we put these one in leaflet-providers.

What do you think of it ? Ready for a pull request ? :)

**Comment by mroswell** [comment]
Hydda seems to have disappeared today.

**Comment by brunob** [comment]
@mroswell it works for me, but i've seen that since a week or two, certain tiles doesn't load correctly with a 503 error eg. : https://b.tile.openstreetmap.se/hydda/full/4/5/5.png

I would be nice if anyone contact https://openstreetmap.se/ team to ask if they are aware of the problem.

**Comment by mroswell** [comment]
@brunob thanks for the suggestion to contact http://openstreetmap.se. I joined the email list (talk-se@openstreetmap.org), and a kind Swede answered my query with a link to this: 

http://openstreetmap.se/nyheter/2017-09-12-english-temp-slow-tiles

> Temporary slow responses from tile server
> OpenStreetMap Sweden have reinstalled the PostGIS database on a new disk, updated new with new data from scratch and cleared out old cache.
> 
> Please expect responses from tile server to be slower than normal for the next few days.

(I also discovered that I could translate 3 words in Swedish "Skickat från min iPhone"

**Comment by brunob** [comment]
@mroswell thx for contacting osm.se and the feedback :)
